### ISSUE TITLE
Javascript or C?

### ISSUE THREAD

**Issue by amanuel2** [charliesome/jsos#10]
Obviously i dont see any Javascript code here.... i was laughing when the descripton said 'An OS Made in Javascript'... that is class :laughing:

**Comment by charliesome** [comment]
There's a fair bit of C code here to support the JS VM, but otherwise the rest of the kernel (including drivers) is in JavaScript:

https://github.com/charliesome/jsos/tree/master/kernel/js

**Comment by amanuel2** [comment]
I Mean... its very suprising javascript can make an OS @charliesome . But the major  downside is speed....
