### ISSUE TITLE
Crarifications About this OS

### ISSUE THREAD

**Issue by adminy** [charliesome/jsos#15]
Instead of building the iso version you decided to build the img version of the OS. This not only takes a lot more space because of the partitions but also more time to make the img drivers and partition logic. Did you run into issues writing an ISO parser or have you not considered this approach for other reasons?

There is some C code, some Ruby code and Some Javascript Code. When an os boots up it does not use the 2 stroke ruby version does it? It's using what the ruby compiled as the javascript jmg files? So Ruby is not part of this os, it's just the "Compile the javascript" as part of the compiling as far as I understood it yes? Also the compiled javascript can interpret javascript ? Can it do what ruby is already doing or what?

I'm  trying to understand all of this and I'm not that familiar with Ruby, but maybe these clarifications will help.

Thank you.

**Comment by Ornataweaver** [comment]
Do you mean Clarification?
